In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\shree\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shree\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\shree\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\shree\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\shree\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\shree\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
# Series - Dataset with 1-D shapes,likely an array or list
# can store any kind of object also can customize 
# its index with diff num,int,str 
import pandas as pd

sr = pd.Series([1,2,3,4,5])
sr.index=["p","o","o","j","a"]
sr

p    1
o    2
o    3
j    4
a    5
dtype: int64

In [23]:
# Customize index while creating a series

sr_index = pd.Series([40,50,60,70,80,90,100],
                     index = ['a','b','c','d','e','f','g'],
                     name="New Series")
sr_index
sr_index['f']
sr_index['e'] = 1
sr_index['b':'e']

# calling with index using
# 1) .loc
sr_index.loc['e':'f']

# 2) .iloc --> access object cells using a numeric index
sr_index.iloc[1:4]

b    50
c    60
d    70
Name: New Series, dtype: int64

In [30]:
sr_index>=70
sr_index[sr_index>80]

# add/merge a series with another series
sr_new = pd.Series([33,55,88])

sr_new_series = pd.concat([sr_index, sr_new])
sr_new_series

a     40
b     50
c     60
d     70
e      1
f     90
g    100
0     33
1     55
2     88
dtype: int64

In [37]:
loan_data = pd.read_csv(
    r"C:\Users\Shree\Desktop\Data_Science\Data_practice\Libraries\Pandas\Dataset\Outlier_Loan_dataset.csv"
)

In [45]:
# missing Values


# loan_data.isna()
# loan_data.isnull()
loan_data.info()
loan_data.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   User_ID               1000 non-null   object
 1   Loan_ID               1000 non-null   object
 2   City                  1000 non-null   object
 3   Age                   980 non-null    float64
 4   Job                   1000 non-null   object
 5   Education             980 non-null    object
 6   Marriage_Status       1000 non-null   object
 7   Account_Balance       1000 non-null   float64
 8   Loan_Amount           980 non-null    float64
 9   Credit_Score          1000 non-null   float64
 10  Debit_Transactions    1000 non-null   float64
 11  Loan_Duration_Months  1000 non-null   int64
 12  Application_Date      1000 non-null   object
 13  Current_Balance       1000 non-null   float64
dtypes: float64(6), int64(1), object(7)
memory usage: 109.5+ KB

User_ID                 1000
Loan_ID                 1000
City                    1000
Age                      980
Job                     1000
Education                980
Marriage_Status         1000
Account_Balance         1000
Loan_Amount              980
Credit_Score            1000
Debit_Transactions      1000
Loan_Duration_Months    1000
Application_Date        1000
Current_Balance         1000
dtype: int64

In [57]:
# can fill or clean data as per requirement
# .fillna(val) --> replaces all NAN val ith static value

loan_data.fillna(0)
# can fills missing value in a specific column
loan_data['Age'].fillna(10) 
# loan_data.ffill()--> ffill()/bfill - fills missing value using prev or next row

0      39.0
1      33.0
2      41.0
3      50.0
4      32.0
       ...
995    32.0
996    52.0
997    41.0
998    29.0
999    40.0
Name: Age, Length: 1000, dtype: float64

In [ ]:
# Dropping missing values

# .dropna()--> removes rows that contain atleast 1 missing value
loan_data.dropna()
# dropnna(how='all') --> removes only rows where all values missing
loan_data.dropna(how='all')
# removes any column that containes at least one missing value
loan_data.dropna(axis=1)
# df.dropna(inplace=True): Modifies the original DataFrame directly rather than returning a new one.

,User_ID,Loan_ID,City,Job,Marriage_Status,Account_Balance,Credit_Score,Debit_Transactions,Loan_Duration_Months,Application_Date,Current_Balance
0,U2169,L532233,Quetta,Clerk,Married,269967.77,554.61,8955.54,45,2024-11-26,139275.96
1,U2807,L516508,Karachi,Driver,Married,246231.68,606.98,14781.58,6,2024-08-18,61391.92
2,U4536,L471613,Peshawar,Manager,Divorced,202981.52,629.32,15126.12,59,2024-01-27,115353.44
3,U9628,L354161,Lahore,Doctor,Married,167653.16,744.38,18308.41,9,2022-09-19,136059.95
4,U8765,L650075,Karachi,Teacher,Married,234911.17,677.83,5431.99,35,2022-08-23,50588.27
...,...,...,...,...,...,...,...,...,...,...,...
995,U1697,L548765,Faisalabad,Driver,Divorced,253507.51,651.42,14657.24,16,2023-11-27,80502.87
996,U7421,L887357,Rawalpindi,Unemployed,Divorced,1192043.64,546.11,19979.87,18,2023-06-29,125286.39
997,U7524,L232943,Rawalpindi,Doctor,Married,155906.27,633.99,36790.37,14,2022-07-20,96334.77
998,U8915,L673563,Faisalabad,Engineer,Divorced,1151079.90,732.17,20656.25,9,2022-12-02,142483.99
999,U4571,L629875,Multan,Driver,Divorced,162754.87,668.03,9063.54,17,2022-10-21,96327.54

In [ ]:
# Data type and conversion

loan_data['Loan_Duration_Months'] = loan_data['Loan_Duration_Months'].astype(float)
loan_data

,User_ID,Loan_ID,City,Age,Job,Education,Marriage_Status,Account_Balance,Loan_Amount,Credit_Score,Debit_Transactions,Loan_Duration_Months,Application_Date,Current_Balance
0,U2169,L532233,Quetta,39.0,Clerk,Matric,Married,269967.77,29744.65,554.61,8955.54,45.0,2024-11-26,139275.96
1,U2807,L516508,Karachi,33.0,Driver,Matric,Married,246231.68,365315.52,606.98,14781.58,6.0,2024-08-18,61391.92
2,U4536,L471613,Peshawar,41.0,Manager,Bachelor,Divorced,202981.52,26227.40,629.32,15126.12,59.0,2024-01-27,115353.44
3,U9628,L354161,Lahore,50.0,Doctor,Matric,Married,167653.16,40761.15,744.38,18308.41,9.0,2022-09-19,136059.95
4,U8765,L650075,Karachi,32.0,Teacher,PhD,Married,234911.17,-6808.44,677.83,5431.99,35.0,2022-08-23,50588.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,U1697,L548765,Faisalabad,32.0,Driver,Matric,Divorced,253507.51,52324.42,651.42,14657.24,16.0,2023-11-27,80502.87
996,U7421,L887357,Rawalpindi,52.0,Unemployed,Master,Divorced,1192043.64,57732.58,546.11,19979.87,18.0,2023-06-29,125286.39
997,U7524,L232943,Rawalpindi,41.0,Doctor,Matric,Married,155906.27,12747.18,633.99,36790.37,14.0,2022-07-20,96334.77
998,U8915,L673563,Faisalabad,29.0,Engineer,Matric,Divorced,1151079.90,60025.29,732.17,20656.25,9.0,2022-12-02,142483.99
999,U4571,L629875,Multan,40.0,Driver,PhD,Divorced,162754.87,45342.23,668.03,9063.54,17.0,2022-10-21,96327.54

In [116]:
loan_amt = loan_data['Loan_Amount'].copy()
loan_amt = pd.to_numeric(loan_amt,errors='coerce')

# before cleaning
print("missing",loan_amt.isna().sum())
print(loan_amt.head())

# fill missing value with median
meadian_val = loan_amt.median()
loan_amt = loan_amt.fillna(meadian_val)

print("Median",meadian_val)
print("Missing after fillna",loan_amt.isna().sum())

# cleaning data 
# i.e loan amount can never be negative
invalid_cnt = (loan_amt<=0).sum()
print("Invalid Values",invalid_cnt)
loan_amt[loan_amt<=0] = meadian_val

# Outlier handle
# IQR calculate
# In pandas to calculate percentile same like in numpy 
# -- use quantile and val
q1 = loan_amt.quantile(0.25)
q3 = loan_amt.quantile(0.75)

IQR = q3-q1
lower = q1 -1.5 *IQR
upper = q3 + 1.5 * IQR

print("Q1 -->",q1,"Q3 -->",q3)
print("IQR -->",IQR)
print("upper Bound -->",upper,"lower Bound -->",lower)

# detect outliers
outliers = loan_amt[(loan_amt < lower) | (loan_amt > upper)]
print("outliers count",outliers.shape[0])

# replae outliers with median
loan_amt_clean = loan_amt.copy()
loan_amt_clean[loan_amt_clean < lower] = meadian_val
loan_amt_clean[loan_amt_clean > upper] = meadian_val

# After Cleaning
print("Missing values",loan_amt_clean.isna().sum())
print("sample Clean data",loan_amt_clean.head())

# Assigning back to main
loan_data['Loan_Amount_Cleaned'] = loan_amt_clean

missing 20
0     29744.65
1    365315.52
2     26227.40
3     40761.15
4     -6808.44
Name: Loan_Amount, dtype: float64
Median 51769.33
Missing after fillna 0
Invalid Values 40
Q1 --> 34974.72 Q3 --> 72391.965
IQR --> 37417.244999999995
upper Bound --> 128517.83249999999 lower Bound --> -21151.147499999992
outliers count 50
Missing values 0
sample Clean data 0    29744.65
1    51769.33
2    26227.40
3    40761.15
4    51769.33
Name: Loan_Amount, dtype: float64

In [115]:
loan_data

,User_ID,Loan_ID,City,Age,Job,Education,Marriage_Status,Account_Balance,Loan_Amount,Credit_Score,Debit_Transactions,Loan_Duration_Months,Application_Date,Current_Balance,Loan_Amount_Cleaned
0,U2169,L532233,Quetta,39.0,Clerk,Matric,Married,269967.77,29744.65,554.61,8955.54,45.0,2024-11-26,139275.96,29744.65
1,U2807,L516508,Karachi,33.0,Driver,Matric,Married,246231.68,365315.52,606.98,14781.58,6.0,2024-08-18,61391.92,51769.33
2,U4536,L471613,Peshawar,41.0,Manager,Bachelor,Divorced,202981.52,26227.40,629.32,15126.12,59.0,2024-01-27,115353.44,26227.40
3,U9628,L354161,Lahore,50.0,Doctor,Matric,Married,167653.16,40761.15,744.38,18308.41,9.0,2022-09-19,136059.95,40761.15
4,U8765,L650075,Karachi,32.0,Teacher,PhD,Married,234911.17,-6808.44,677.83,5431.99,35.0,2022-08-23,50588.27,51769.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,U1697,L548765,Faisalabad,32.0,Driver,Matric,Divorced,253507.51,52324.42,651.42,14657.24,16.0,2023-11-27,80502.87,52324.42
996,U7421,L887357,Rawalpindi,52.0,Unemployed,Master,Divorced,1192043.64,57732.58,546.11,19979.87,18.0,2023-06-29,125286.39,57732.58
997,U7524,L232943,Rawalpindi,41.0,Doctor,Matric,Married,155906.27,12747.18,633.99,36790.37,14.0,2022-07-20,96334.77,12747.18
998,U8915,L673563,Faisalabad,29.0,Engineer,Matric,Divorced,1151079.90,60025.29,732.17,20656.25,9.0,2022-12-02,142483.99,60025.29
999,U4571,L629875,Multan,40.0,Driver,PhD,Divorced,162754.87,45342.23,668.03,9063.54,17.0,2022-10-21,96327.54,45342.23